# Generated by Django 4.2.13 on 2024-07-02 23:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_contacto_mensaje_cifrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='contenido',
            field=ckeditor.fields.RichTextField(default='Información no disponible'),
            preserve_default=False,
        ),
    ]
