# Generated by Django 4.2.13 on 2024-07-04 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_imagenproyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproyecto',
            name='imagen',
            field=models.ImageField(upload_to='proyectos/set1/'),
        ),
        migrations.AlterField(
            model_name='imagenproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_set1', to='myportfolio.proyecto'),
        ),
        migrations.CreateModel(
            name='ImagenProyecto3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='proyectos/set3/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_set3', to='myportfolio.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProyecto2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='proyectos/set2/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_set2', to='myportfolio.proyecto')),
            ],
        ),
    ]
